### ISSUE TITLE
catkin_make failed

### ISSUE THREAD

**Issue by ZOUJIASHUAI** [Liansheng-Wang/LIO-Lite#1]
/home/jason/LIO-Lite/src/LIO-Lite/src/laser_mapping.cc:3:10: fatal error: execution: 没有那个文件或目录
 #include <execution>
          ^~~~~~~~~~~
compilation terminated.
LIO-Lite/CMakeFiles/lio_lite.dir/build.make:75: recipe for target 'LIO-Lite/CMakeFiles/lio_lite.dir/src/laser_mapping.cc.o' failed
make[2]: *** [LIO-Lite/CMakeFiles/lio_lite.dir/src/laser_mapping.cc.o] Error 1
make[2]: *** 正在等待未完成的任务....
/home/jason/LIO-Lite/src/LIO-Lite/src/pointcloud_preprocess.cc:4:10: fatal error: execution: 没有那个文件或目录
 #include <execution>
          ^~~~~~~~~~~
compilation terminated.
LIO-Lite/CMakeFiles/lio_lite.dir/build.make:89: recipe for target 'LIO-Lite/CMakeFiles/lio_lite.dir/src/pointcloud_preprocess.cc.o' failed
make[2]: *** [LIO-Lite/CMakeFiles/lio_lite.dir/src/pointcloud_preprocess.cc.o] Error 1
CMakeFiles/Makefile2:2350: recipe for target 'LIO-Lite/CMakeFiles/lio_lite.dir/all' failed
make[1]: *** [LIO-Lite/CMakeFiles/lio_lite.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j20 -l20" failed

**Comment by ZOUJIASHUAI** [comment]
@Liansheng-Wang please help

**Comment by Liansheng-Wang** [comment]
看错误应该是系统没有安装 ttb,  一个多线程并发的库，你是使用的什么系统？

**Comment by Liansheng-Wang** [comment]
> @Liansheng-Wang please help
看错误应该是系统没有安装 ttb, 一个多线程并发的库，你是使用的什么系统？

**Comment by ZOUJIASHUAI** [comment]
> > @Liansheng-Wang please help
> > 看错误应该是系统没有安装 ttb, 一个多线程并发的库，你是使用的什么系统？

不是吧,代码提示是没有#include <execution>的头文件,我运行其他定位的时候已经装了TTB,系统是ubuntu18
![2024-02-29 15-51-23 的屏幕截图](https://github.com/Liansheng-Wang/LIO-Lite/assets/19969444/a9945a20-e708-4a7e-8a74-e4abb7b0d969)

**Comment by ZOUJIASHUAI** [comment]
https://blog.csdn.net/nvlidewoniu666/article/details/134673685 解决了

**Comment by ZOUJIASHUAI** [comment]
https://blog.csdn.net/weixin_32207065/article/details/112270765

**Comment by ZOUJIASHUAI** [comment]
https://blog.csdn.net/weixin_32207065/article/details/112270765

**Comment by ZOUJIASHUAI** [comment]
https://blog.csdn.net/qq_39779233/article/details/125450608    https://blog.csdn.net/weixin_32207065/article/details/112270765
